# Autogenerated by devscripts/update-version.py

__version__ = '2025.05.12.025323'

RELEASE_GIT_HEAD = '34f24f42a1a9dfea2cffcac597fb4379c426283a'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'kclauhk/yt-dlp'

ORIGIN = 'kclauhk/yt-dlp'

_pkg_version = '2025.05.12.025323'
