# Autogenerated by devscripts/update-version.py

__version__ = '2026.01.19.070934'

RELEASE_GIT_HEAD = '1e469947f951f9dbfd076a039b15163b102afb1f'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'kclauhk/yt-dlp'

ORIGIN = 'kclauhk/yt-dlp'

_pkg_version = '2026.01.19.070934'
