# Autogenerated by devscripts/update-version.py

__version__ = '2024.08.14.012143'

RELEASE_GIT_HEAD = '5ebcf298fb541020dd51e03fbbab0cddc34c767c'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'kclauhk/yt-dlp'

ORIGIN = 'kclauhk/yt-dlp'

_pkg_version = '2024.08.14.012143'
